-- ============================================================
-- 五金厂管理系统 · 云端数据库建表脚本（PostgreSQL / Supabase）
-- ============================================================
-- 【使用方法】
--   1. 打开 Supabase 后台 → 左侧菜单 "SQL Editor"（SQL 编辑器）
--   2. 点 "New query"（新建查询），把本文件全部内容粘贴进去
--   3. 点右上角 "Run"（▶ 运行）执行
--   4. 看到 "Success. No rows returned" 即表示建表成功
--
-- 【设计说明】
--   * 登录身份由 Supabase Auth 提供，每个注册用户得到一个 uuid
--   * 所有业务表都带 user_id 列，通过 RLS 行级安全策略
--     保证"每个用户只能看到/修改自己的数据"（云端隔离，安全）
--   * id 用 bigint 自增，且允许客户端指定（generated by default），
--     这样把本地旧数据迁移上云时能保留原 id，外键引用不会断
--   * 原系统本地 users 表不再需要，改用 profiles 表存显示用户名
-- ============================================================

-- 0) 扩展：uuid 生成器（Supabase 默认已开启，保险起见）
create extension if not exists "pgcrypto";

-- 1) 用户档案表（登录身份来自 Supabase Auth，这里只存显示用用户名）
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  username    text not null,
  created_at  timestamptz default now()
);

-- 2) 各业务表（统一带 user_id 隔离列） ------------------------------

-- 客户管理
create table if not exists public.customers (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  code        text,
  name        text,
  contact     text,
  phone       text,
  email       text,
  address     text,
  credit      numeric default 0,
  level       text,
  note        text
);

-- 产品管理（inQty/outQty/costTotal/stockValue/prodCost/totalCost 为列表计算字段，不入库）
create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  code        text,
  name        text,
  spec        text,
  category    text,
  unit        text,
  location    text,
  initStock   numeric default 0,
  stock       numeric default 0,
  safety      numeric default 0,
  costMaterial numeric default 0,
  costLabor   numeric default 0,
  processIds  jsonb,
  costMfg     numeric default 0
);

-- 员工管理
create table if not exists public.employees (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  code        text,
  name        text,
  dept        text,
  position    text,
  hireDate    date,
  phone       text,
  status      text,
  note        text
);

-- 固定工资（net/unitWage/totalWage 为计算字段，不入库）
create table if not exists public.salaries (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  employeeId  bigint,
  periodType  text,
  workSchedule text,
  contractStart date,
  contractEnd date,
  base        numeric default 0,
  note        text
);

-- 计件工资（processCostTotal/unitWage/total 为计算字段，不入库）
create table if not exists public.piecerate (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  employeeId  bigint,
  date        date,
  productId   bigint,
  spec        text,
  processIds  jsonb,
  processes   jsonb,
  unit        text,
  qty         numeric default 0,
  unitPrice   numeric default 0,
  note        text
);

-- 加班工资（amount 为计算字段，不入库）
create table if not exists public.overtime (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  employeeId  bigint,
  date        date,
  category    text,
  hours       numeric default 0,
  rate        numeric default 0,
  note        text
);

-- 扣款工资
create table if not exists public.deduction (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  employeeId  bigint,
  date        date,
  category    text,
  amount      numeric default 0,
  note        text
);

-- 报价管理（total/costMaterial/costLabor/costMfg/totalCost/profit/margin 为计算字段，不入库）
create table if not exists public.quotations (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  code        text,
  date        date,
  customerId  bigint,
  productId   bigint,
  spec        text,
  unit        text,
  qty         numeric default 0,
  unitPrice   numeric default 0,
  priceType   text,
  taxRate     numeric default 0,
  received    numeric default 0,
  payStatus   text,
  dueDate     date,
  status      text,
  note        text
);

-- 排单计划
create table if not exists public.schedules (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  customerId  bigint,
  productId   bigint,
  spec        text,
  processId   bigint,
  qty         numeric default 0,
  unit        text,
  dueDate     date,
  priority    text,
  line        text,
  employeeIds jsonb,
  status      text,
  note        text
);

-- 进出货记录
create table if not exists public.stockflows (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  productId   bigint,
  type        text,
  date        date,
  qty         numeric default 0,
  price       numeric default 0,
  refNo       text,
  note        text
);

-- 运营费用
create table if not exists public.expenses (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  date        date,
  category    text,
  amount      numeric default 0,
  payMethod   text,
  note        text
);

-- 预算
create table if not exists public.budgets (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  year        integer,
  month       text,
  category    text,
  amount      numeric default 0,
  note        text
);

-- 工资调整（salaryadjustments）
create table if not exists public.salaryadjustments (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  employeeId  bigint,
  bucket      text,
  fixed       numeric default 0,
  piece       numeric default 0,
  ot          numeric default 0,
  ded         numeric default 0,
  actDays     integer default 0,
  updatedAt   timestamptz
);

-- 设置（KV 表：key/value）
create table if not exists public.settings (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  key         text,
  value       text
);

-- 分类 / 单位 / 工序（仅 name 字段）
create table if not exists public.categories (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  name        text
);
create table if not exists public.units (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  name        text
);
create table if not exists public.processes (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null,
  name        text
);

-- 3) 开启行级安全（RLS）并为每张表写隔离策略 -----------------------
--    规则：只有"当前登录用户"能读写自己 user_id 的行
do $$
declare t text;
begin
  foreach t in array array[
    'customers','products','employees','salaries','piecerate','overtime',
    'deduction','quotations','schedules','stockflows','expenses','budgets',
    'salaryadjustments','settings','categories','units','processes'
  ]
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists "own_rows" on public.%I;', t);
    execute format(
      'create policy "own_rows" on public.%I for all using (auth.uid() = user_id) with check (auth.uid() = user_id);',
      t
    );
  end loop;
end $$;

-- profiles 表策略：用户只能看/建自己的档案
alter table public.profiles enable row level security;
drop policy if exists "own_profile_select" on public.profiles;
create policy "own_profile_select" on public.profiles for select using (auth.uid() = id);
drop policy if exists "own_profile_insert" on public.profiles;
create policy "own_profile_insert" on public.profiles for insert with check (auth.uid() = id);

-- 4) 注册时自动建 profile（读取注册时传入的 username） ------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- 执行完上面全部内容后，回到应用即可注册/登录并自动建库。
-- 可选：把本地旧数据迁移上云，请使用应用内"导入本地数据"按钮。
-- ============================================================
